### Text cleaning and Preprocessing
Lowercasing

In [281]:
import pandas as pd
import numpy as np

In [282]:
df = pd.read_csv('tweet_emotions.csv')

In [283]:
df.head()

     tweet_id   sentiment                                            content
0  1956967341       empty  @tiffanylue i know  i was listenin to bad habi...
1  1956967666     sadness  Layin n bed with a headache  ughhhh...waitin o...
2  1956967696     sadness                Funeral ceremony...gloomy friday...
3  1956967789  enthusiasm               wants to hang out with friends SOON!
4  1956968416     neutral  @dannycastillo We want to trade with someone w...

In [284]:
df['content'][0]

'@tiffanylue i know  i was listenin to bad habit earlier and i started freakin at his part =['

In [285]:
df['content'] = df['content'].str.lower()

In [286]:
## HTML tags removal
import re

In [287]:
text = '<p>This is a <b>bold</b> text.</p>'

In [288]:
cleaned_data = re.sub(r'<.*?>', '', text)

In [289]:
data = pd.DataFrame({
    'col': ['Hello, <h1> I  am Dharmender </h1>','<a href="https://www.google.com">Google</a>',
            'This is a <b>bold</b> text.',
            'No HTML tags here.']
})

In [290]:
data

                                           col
0           Hello, <h1> I  am Dharmender </h1>
1  <a href="https://www.google.com">Google</a>
2                  This is a <b>bold</b> text.
3                           No HTML tags here.

In [291]:
def html_tags_removal(text):
    empty_html = []
    for i in text: 
        empty_html.append(re.sub(r'<.*?>', '', text))
    return empty_html

In [292]:
data['col'] = data['col'].apply(html_tags_removal)

In [293]:
data['col']

0    [Hello,  I  am Dharmender , Hello,  I  am Dhar...
1    [Google, Google, Google, Google, Google, Googl...
2    [This is a bold text., This is a bold text., T...
3    [No HTML tags here., No HTML tags here., No HT...
Name: col, dtype: object

In [294]:
text = "hey https://darion.com visit my website."

In [295]:
re.sub(r'https?://\S+|www\.\S+',"",text)

'hey  visit my website.'

In [296]:
def url_removal(text):
    return re.sub(r'https?://\S+|www\.\S+',"",text)

In [297]:
df.columns

Index(['tweet_id', 'sentiment', 'content'], dtype='object')

In [298]:
df['content'].isnull().sum()

0

In [299]:
df.dropna(subset=['content'],inplace=True)

In [300]:
df['content'].isnull().sum()

0

In [301]:
df['content'] = df['content'].apply(url_removal)[1]

In [302]:
text = 'Hey , I am dharm ! how are you ?'

In [303]:
re.sub(r'[^\w\s]',"",text)

'Hey  I am dharm  how are you '

In [304]:
def remove_punctuations(text):
    # without_punc = []
    return re.sub(r'[^\w\s]',"",text)

In [305]:
df['content'] = df['content'].apply(remove_punctuations)

In [306]:
slang_dict = {"asap":"As soon as possible","gn":"good morning","yolo":"You only live once",
              "lol":"lots of laugh"}

In [307]:
slang = pd.DataFrame({"slang":["Hey call me asap","hey hello gn",'lol that was funny','hey yolo you know it.']})

In [308]:
slang

                   slang
0       Hey call me asap
1           hey hello gn
2     lol that was funny
3  hey yolo you know it.

In [309]:
text = slang['slang'][0]

In [310]:
def expand_slang(text,slang_dict):
    text = text.lower()
    words = text.split()
    return " ".join([slang_dict.get(word, word) for word in words])

In [311]:
expand_slang(text,slang_dict)

'hey call me As soon as possible'

In [312]:
slang

                   slang
0       Hey call me asap
1           hey hello gn
2     lol that was funny
3  hey yolo you know it.

### Text cleaning and Preprocessing
- Lowercasing
- Words with slang and abbreviations
- Words with special characters and punctuation
- Stop words
- Stemming and Lemmatization
- Removing extra spaces and newlines
- Removing URLs, mentions, and hashtags
- Removing numbers
- Removing emojis and emoticons

#### Advanced Text Preprocessing
- Handling wrong spellings/typos

In [313]:
text = "hey How ar you , I ws searchi for you yestrday I couln find youuu !"

In [314]:
from textblob import TextBlob

In [315]:
textblb = TextBlob(text)

In [316]:
text

'hey How ar you , I ws searchi for you yestrday I couln find youuu !'

In [317]:
textblb.correct().string

'hey Now ar you , I was search for you yesterday I could find you !'

In [318]:
from nltk.corpus import stopwords
st = stopwords.words('english')
len(st)

198

In [319]:
text = "Hey how are you I am fine I was looking for you"

In [320]:
without_stops = []
for i in text.split(): 
    if i not in st:
        without_stops.append(i)
print(without_stops)

['Hey', 'I', 'fine', 'I', 'looking']

In [321]:
def stopwords_removal(text):
    without_stops = []
    for i in text.split(): 
        if i not in st:
            without_stops.append(i)
    return without_stops

In [322]:
df['content'] = df['content'].apply(stopwords_removal)

In [323]:
df['content']

0        [layin, n, bed, headache, ughhhhwaitin, call]
1        [layin, n, bed, headache, ughhhhwaitin, call]
2        [layin, n, bed, headache, ughhhhwaitin, call]
3        [layin, n, bed, headache, ughhhhwaitin, call]
4        [layin, n, bed, headache, ughhhhwaitin, call]
                             ...
39995    [layin, n, bed, headache, ughhhhwaitin, call]
39996    [layin, n, bed, headache, ughhhhwaitin, call]
39997    [layin, n, bed, headache, ughhhhwaitin, call]
39998    [layin, n, bed, headache, ughhhhwaitin, call]
39999    [layin, n, bed, headache, ughhhhwaitin, call]
Name: content, Length: 40000, dtype: object

### Handling Emoticons and Emojis
- Emoticons and emojis can convey emotions and sentiments in text data.
- They can be used to enhance sentiment analysis and emotion detection tasks.
- It is important to consider the context in which emoticons and emojis are used, as they can have different meanings in different contexts.
- Some common emoticons include :) for happy, :( for sad, and :D for laughing.
- Emojis can be represented using Unicode characters, and there are various libraries available for handling emojis in text data, such as the `emoji` library in Python.

Ways to handle emoticons and emojis in text data:
1. Remove them: This can be done using regular expressions or by using libraries that specifically target emoticons and emojis.
2. Understand their meaning: This can be done by creating a mapping of emoticons and emojis to their corresponding meanings or sentiments. For example, :) can be mapped to "happy" and :( can be mapped to "sad".

In [324]:
def remove_emojis(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [325]:
data = pd.DataFrame({
    'data_with_emoji': 
    ['Hello 😊', 'Good morning ☀️', 'I love Python 🐍']

})

In [326]:
data

   data_with_emoji
0          Hello 😊
1  Good morning ☀️
2  I love Python 🐍

In [327]:
data['data_with_emoji'] = data['data_with_emoji'].apply(remove_emojis)

In [328]:
data

   data_with_emoji
0           Hello
1  Good morning ☀️
2   I love Python

In [329]:
import pandas as pd

In [330]:
d = pd.read_csv('test_data_cleaning.csv')

In [331]:
## split() -- ## word tokenize

In [332]:
sent_1 = "I am going to delhi"

In [333]:
sent_1.split()  # default is space

['I', 'am', 'going', 'to', 'delhi']

In [334]:
para = "I am going to delhi. I will be there by 5 PM. Let's meet at the cafe."

In [335]:
para.split('.')

['I am going to delhi',
 ' I will be there by 5 PM',
 " Let's meet at the cafe",
 '']

In [336]:
sent_2 = "Hi i am in delhi"

In [337]:
sent_2.split()

['Hi', 'i', 'am', 'in', 'delhi']

In [338]:
import re

In [339]:
re.findall(r'[\w]+', sent_1)  # \w is for word character and + is for one or more character

['I', 'am', 'going', 'to', 'delhi']

In [340]:
text = "Hey how are you ? I am Fine ! I was something for you."

In [341]:
re.compile(r'[.!?]').split(text)

['Hey how are you ', ' I am Fine ', ' I was something for you', '']

In [342]:
## NLTK  --> Natural Language Tool Kit

## word_splitting, sentence_splitting

In [343]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [344]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/dharmender/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [345]:
sent_1 = "I have a Ph.D. in A.I."

In [346]:
word_tokenize(sent_1)

['I', 'have', 'a', 'Ph.D.', 'in', 'A.I', '.']

In [347]:
sent_3 = "A 5km ride costs $10.50"

In [348]:
word_tokenize(sent_3)

['A', '5km', 'ride', 'costs', '$', '10.50']

In [349]:
### Spacy 
import spacy
nlp = spacy.load('en_core_web_sm')

In [350]:
## English dictionary

In [351]:
text_1 = "I have a Ph.D. in A.I."
text_2 = "we're here to help you. You can reach us at 123-456-7890 or email us at abc@gmail.com"
text_3 = "A 5km ride costs $10.50"

In [352]:
token_1 = nlp(text_1)
for i in token_1:
    print(i)

I
have
a
Ph.D.
in
A.I.

In [353]:
token_2 = nlp(text_2)
for i in token_2:
    print(i)

we
're
here
to
help
you
.
You
can
reach
us
at
123
-
456
-
7890
or
email
us
at
abc@gmail.com

In [354]:
from nltk.stem import PorterStemmer

In [355]:
ps = PorterStemmer()

In [356]:
words = ["run", "runner", "running", "ran", "runs"]

In [357]:
for i in words:
    print(ps.stem(i))

run
runner
run
ran
run

In [358]:
from nltk.stem import WordNetLemmatizer

In [359]:
from nltk.corpus import wordnet
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     /home/dharmender/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [360]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /home/dharmender/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [361]:
lemma = WordNetLemmatizer()

In [362]:
lemma.lemmatize("running", pos='v')

'run'

In [363]:
lemma.lemmatize("better", pos='a')

'good'

In [364]:
lemma.lemmatize("mice", pos='n')

'mouse'

In [365]:
words = ['running','stories','runs','ran','easily','fairly']

In [366]:
lemma.lemmatize("runs", pos='a')

'runs'

### Text Representation into Vectors
- Text data needs to be converted into a numerical format for machine learning models to process it.
- Common techniques for text representation include:
1. Bag of Words (BoW): This technique represents text as a bag of its words, disregarding grammar and word order but keeping multiplicity. It creates a vector of word counts for each document.
2. Term Frequency-Inverse Document Frequency (TF-IDF): This technique weighs the importance of words in a document based on their frequency in the document and their inverse frequency across all documents. It creates a vector of TF-IDF scores for each word in the document.
3. Word Embeddings: This technique represents words as dense vectors in a continuous vector space. Word embeddings capture semantic relationships between words, allowing for better performance in tasks like sentiment analysis and language modeling. Common word embedding techniques include Word2Vec, GloVe, and FastText.

### Encoding --> 
1. One-Hot Encoding: This technique represents each word as a binary vector, where the length of the vector is equal to the size of the vocabulary. Each position in the vector corresponds to a specific word in the vocabulary, and the value is 1 if the word is present in the document and 0 otherwise.
2. Label Encoding: This technique assigns a unique integer to each word in the vocabulary. The value of the integer corresponds to the index of the word in the vocabulary. This technique is often used for categorical variables, but it can also be applied to text data by treating each word as a category. However, it is important to note that label encoding can introduce ordinal relationships between words, which may not be desirable in certain cases.
3. Ordinal Encoding: This technique is similar to label encoding, but it assigns a unique integer to each word based on its frequency in the corpus. The most frequent word is assigned the integer 1, the second most frequent word is assigned the integer 2, and so on. This technique can be useful for capturing the importance of words in the corpus, but it can also introduce ordinal relationships between words, which may not be desirable in certain cases.
4. Binary Encoding: This technique represents each word as a binary vector, where the length of the vector is equal to the size of the vocabulary. Each position in the vector corresponds to a specific word in the vocabulary, and the value is 1 if the word is present in the document and 0 otherwise. However, unlike one-hot encoding, binary encoding allows for multiple words to be represented in the same vector, which can help reduce the dimensionality of the data.
5. Hashing Encoding: This technique uses a hash function to convert each word into a fixed-length vector. The hash function maps each word to a specific index in the vector, and the value at that index is incremented for each occurrence of the word in the document. This technique can be useful for handling large vocabularies, but it can also lead to collisions, where different words are mapped to the same index in the vector.

## One Hot Encoding And Bag of Words in Text Vectorization

#### One-Hot Encoding
It is type of text vectorization when we convert the text into vectors such that every unique word will have there corresponding vector.

In [367]:
movie = pd.read_csv('IMDB_Dataset.csv')

In [368]:
movie.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [369]:
movie['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [370]:
movie.shape

(50000, 2)

In [371]:
''' 
50000 * 300 --> total words --> 15 crore ---> corpus
vocabulary --> 2 crore (unique words)
vector --> 3 crore values
total 15 crore words & every word --> shape --->[2 crore] 
'''

' \n50000 * 300 --> total words --> 15 crore ---> corpus\nvocabulary --> 2 crore (unique words)\nvector --> 3 crore values\ntotal 15 crore words & every word --> shape --->[2 crore] \n'

In [372]:
d = pd.DataFrame({'col':['People Love AI','AI Love AI-ML','AI-ML Love Love','Love People People']})

In [373]:
d

                  col
0      People Love AI
1       AI Love AI-ML
2     AI-ML Love Love
3  Love People People

In [374]:
from sklearn.feature_extraction.text import CountVectorizer

In [375]:
cv = CountVectorizer()

In [376]:
count = cv.fit_transform(d['col']).toarray()

In [377]:
count

array([[1, 1, 0, 1],
       [2, 1, 1, 0],
       [1, 2, 1, 0],
       [0, 1, 0, 2]])

In [378]:
cv.vocabulary_

{'people': 3, 'love': 1, 'ai': 0, 'ml': 2}

#### Properties of Bag of Words
1. In BoW, shapes will remain the same just because every sentence vectorization inclines to the vocabulary itself. 
2. Out of vocabulary words will be ignored in BoW.
3. Semantic Relationship --> BoW does not capture the semantic relationship between words. It treats each word as an independent feature, which can lead to loss of context and meaning in the text data. For example, the sentences "I love AI" and "AI loves me" would have the same BoW representation, even though they convey different meanings.
4. Sparsity --> BoW can lead to sparse vectors, especially when dealing with large vocabularies. This can make it difficult for machine learning models to learn from the data, as many features will have a value of zero.
5. Dimensionality --> BoW can lead to high-dimensional vectors, especially when dealing with large vocabularies. This can make it computationally expensive to process the data and can also lead to overfitting in machine learning models.
6. Ordering of the words --> BoW does not capture the ordering of words in a sentence.

## N-grams and TF-IDF in Text Vectorization

#### One-Hot Encoding : 
- Not even optimal in a way such that we can feed the data to our model. (Shape issue)

#### Bag of Words :
- IT is not having shape issue but it has word sequence is something that has not been taken care of. (Word sequence issue)
- Different meaning sentences can still be considered bit-similar to each other in BoW. (Semantic relationship issue)

#### N-grams (Bi-grams, Tri-grams, etc.) :
- In N-grams, rather than taking a (unique word in the vocabulary), we take the sequence of words in the vocabulary.

- In Bi-grams, (2-consecutive tokens)  are taken together in the vocabulary. 
- In Tri-grams, (3-consecutive tokens) are taken together in the vocabulary.
- In N-grams, (sequential - information) is maintained in the vocabulary.

- For the coding part of (N-grams), we are still going to use countvectorizer --> parameter --> [ngram_range = (1,2)] --> this will take care of both unigrams and bigrams.

In [379]:
cv = CountVectorizer(ngram_range=(2,2))

In [380]:
cv.fit_transform(d['col']).toarray()

array([[0, 0, 1, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1]])

In [381]:
cv.get_feature_names_out()

array(['ai love', 'ai ml', 'love ai', 'love love', 'love people',
       'ml love', 'people love', 'people people'], dtype=object)

In [382]:
cv.vocabulary_

{'people love': 6,
 'love ai': 2,
 'ai love': 0,
 'ai ml': 1,
 'ml love': 5,
 'love love': 3,
 'love people': 4,
 'people people': 7}

In [383]:
## Unigram --> single word, min = 1, max = 1
cv = CountVectorizer(ngram_range=(1,1))

In [384]:
cv.fit_transform(d['col']).toarray()

array([[1, 1, 0, 1],
       [2, 1, 1, 0],
       [1, 2, 1, 0],
       [0, 1, 0, 2]])

In [385]:
d['col']

0        People Love AI
1         AI Love AI-ML
2       AI-ML Love Love
3    Love People People
Name: col, dtype: object

In [386]:
cv.get_feature_names_out()

array(['ai', 'love', 'ml', 'people'], dtype=object)

In [387]:
cv.vocabulary_

{'people': 3, 'love': 1, 'ai': 0, 'ml': 2}

In [388]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [389]:
tf = TfidfVectorizer()

In [390]:
tf.fit_transform(d['col']).toarray()

array([[0.55953044, 0.4574528 , 0.        , 0.69113141],
       [0.80359984, 0.32849776, 0.49630284, 0.        ],
       [0.43855558, 0.71709584, 0.54170339, 0.        ],
       [0.        , 0.31418628, 0.        , 0.94936136]])

In [391]:
tf.get_feature_names_out()

array(['ai', 'love', 'ml', 'people'], dtype=object)

In [392]:
tf.idf_

array([1.22314355, 1.        , 1.51082562, 1.51082562])

## Word2Vec Vector Embeddings in Text Vectorization: 
- Word2Vec is a popular word embedding technique that represents words as dense vectors in a continuous vector space.
- Word2Vec captures semantic relationships between words, allowing for better performance in tasks like sentiment analysis and language modeling.
- Word2Vec can be trained using two main architectures: Continuous Bag of Words (CBOW) and Skip-Gram.
- CBOW predicts the target word based on the context words, while Skip-Gram predicts the context words based on the target word.
- Word2Vec can be implemented using libraries like Gensim in Python, which provides efficient implementations of the Word2Vec algorithm.

#### Word Embeddings:
- Numeric Representation of words in a continuous vector space.
- Dense vectors that capture semantic relationships between words.
- Common techniques include Word2Vec, GloVe, and FastText.

In [393]:
import gensim

In [394]:
from gensim.models import KeyedVectors

In [395]:
path = "GoogleNews-vectors-negative300.bin.gz"
model = KeyedVectors.load_word2vec_format(path, binary=True,limit=100000)

In [396]:
len(model['man'])

300

In [397]:
model['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [398]:
## Arithmetic operations on word vectors

In [399]:
model['king'] - model['queen']

array([ 1.20727539e-01,  1.73339844e-01,  7.79418945e-02,  1.61132812e-02,
       -1.57470703e-01,  5.27343750e-02,  1.83105469e-01,  1.85546875e-02,
        2.48535156e-01,  3.07617188e-01, -1.66503906e-01,  7.81250000e-02,
       -2.81738281e-01, -2.40859985e-02, -3.00781250e-01, -2.82714844e-01,
       -3.80859375e-02,  5.20935059e-02, -1.95312500e-02,  3.46679688e-02,
       -5.37109375e-02, -2.39257812e-02,  2.95898438e-01,  2.55371094e-01,
        3.56445312e-02, -1.23535156e-01,  5.66406250e-02, -3.19824219e-02,
        1.53320312e-01,  1.35864258e-01,  2.60742188e-01,  1.92626953e-01,
        2.07031250e-01,  1.87500000e-01,  3.32031250e-02,  2.15820312e-01,
       -5.71289062e-02, -2.57812500e-01,  1.65039062e-01, -1.07421875e-02,
        3.17382812e-02,  1.84570312e-01,  1.36718750e-02,  1.70288086e-01,
        1.66015625e-01,  8.88671875e-02, -1.05743408e-01, -1.12304688e-01,
       -2.10937500e-01, -2.52258301e-01, -1.44165039e-01,  5.95703125e-02,
       -3.12744141e-01,  5.13916016e-02,  0.00000000e+00,  5.94635010e-02,
        1.99218750e-01,  1.15966797e-01, -7.12890625e-02,  6.56738281e-02,
        5.07812500e-02,  1.67968750e-01,  5.93872070e-02,  1.95312500e-03,
       -7.71484375e-02,  3.61328125e-02, -8.81958008e-02, -2.74414062e-01,
        5.66406250e-02,  1.64550781e-01, -3.80859375e-02, -1.61621094e-01,
        3.41796875e-02, -4.10156250e-02,  7.82470703e-02, -1.16210938e-01,
       -2.66601562e-01,  9.82666016e-03,  3.41796875e-02, -7.76367188e-02,
        1.98974609e-01,  6.66503906e-02, -2.56835938e-01,  4.60205078e-02,
        1.23779297e-01, -1.07910156e-01, -1.56250000e-02, -1.30737305e-01,
       -1.45507812e-01, -6.86035156e-02, -9.76562500e-02,  9.81445312e-02,
       -9.27734375e-02, -1.28662109e-01, -1.62597656e-01, -1.12304688e-02,
       -9.87548828e-02,  6.44531250e-02, -4.78515625e-02, -2.35931396e-01,
        6.82373047e-02,  2.15332031e-01, -1.46972656e-01, -1.13281250e-01,
        1.75781250e-01,  6.78710938e-02,  1.46484375e-01,  6.97021484e-02,
        1.94824219e-01,  1.10839844e-01,  3.51562500e-02,  1.20117188e-01,
       -1.25486374e-01, -2.77343750e-01,  1.23046875e-01, -1.87500000e-01,
       -1.71981812e-01,  6.93359375e-02, -4.68750000e-02,  7.81250000e-02,
        8.30078125e-02,  2.32910156e-01, -1.94213867e-01,  7.71484375e-02,
       -1.77490234e-01, -1.11755371e-01,  1.62353516e-01, -1.87500000e-01,
        1.73339844e-02, -1.91894531e-01, -7.81250000e-02, -8.78906250e-03,
        2.04833984e-01, -2.30468750e-01,  1.11572266e-01, -8.00781250e-02,
        1.57714844e-01,  1.04492188e-01,  2.44140625e-02,  2.07519531e-01,
        1.06445312e-01,  1.46484375e-02,  1.32568359e-01,  1.36230469e-01,
        1.56738281e-01, -2.51220703e-01,  8.86917114e-02, -3.68164062e-01,
        5.17578125e-02,  3.03466797e-01, -1.26708984e-01, -8.78906250e-03,
       -3.28613281e-01,  7.22656250e-02, -1.20117188e-01,  1.53808594e-01,
       -2.17285156e-02,  7.98339844e-02, -9.96093750e-02, -7.08007812e-02,
       -1.13769531e-01, -1.73034668e-01, -5.85937500e-02, -2.09136963e-01,
       -7.66601562e-02, -1.16699219e-01,  1.09375000e-01,  1.89453125e-01,
        4.02526855e-02, -4.39453125e-02, -4.68750000e-02, -1.46484375e-02,
       -3.90625000e-03,  8.61816406e-02,  2.30468750e-01,  1.60644531e-01,
        9.71984863e-02, -1.33178711e-01,  5.28564453e-02,  2.81372070e-02,
       -3.02734375e-02, -1.83105469e-01, -1.51367188e-01, -6.68945312e-02,
       -1.66046143e-01,  1.32324219e-01,  1.33789062e-01,  8.17871094e-02,
        3.55468750e-01, -1.32812500e-01,  1.35742188e-01,  7.73925781e-02,
       -1.37084961e-01, -8.61206055e-02, -1.91894531e-01, -2.09838867e-01,
       -1.49353027e-01, -1.86035156e-01,  1.07910156e-01, -7.42187500e-02,
       -1.10794067e-01,  1.56250000e-01,  1.28173828e-01,  1.41601562e-02,
        5.16357422e-02,  5.41992188e-02,  4.88281250e-04, -7.22656250e-02,
       -1.09863281e-01, -1.00585938e-01, -1.22070312e-02,  1.99707031e-01,
       -3.32031250e-02, -4.49218750e-02, -1.69921875e-01,  4.69055176e-02,
        1.20643616e-01,  5.85937500e-03, -2.50976562e-01, -1.30554199e-01,
       -9.61914062e-02, -1.90673828e-01, -6.64062500e-02, -1.55181885e-01,
        1.31713867e-01,  1.47476196e-01, -2.09960938e-01,  2.06542969e-01,
        3.22265625e-02, -4.78515625e-02,  4.19921875e-02, -2.53906250e-02,
        3.51562500e-02, -1.01379395e-01, -2.89062500e-01,  1.79687500e-01,
        1.16455078e-01,  7.24487305e-02, -3.82156372e-02, -1.46484375e-02,
       -1.65039062e-01,  7.81250000e-03, -1.37580872e-01,  1.18774414e-01,
        3.90625000e-03, -1.17858887e-01, -8.49609375e-02,  3.41796875e-02,
        2.07031250e-01, -3.02734375e-02,  2.68554688e-03,  1.12884521e-01,
       -5.66406250e-02, -2.63671875e-02,  1.02539062e-01,  3.71093750e-02,
       -1.54296875e-01, -8.05664062e-02,  1.38671875e-01, -3.12500000e-02,
        1.41601562e-02, -8.10546875e-02,  1.80664062e-01,  1.36718750e-01,
       -4.41894531e-02, -1.98730469e-01, -2.14843750e-02, -2.83203125e-01,
        7.42187500e-02,  4.49218750e-02,  2.19726562e-01, -6.83593750e-03,
       -8.91113281e-02, -2.00195312e-02, -3.08593750e-01,  1.16210938e-01,
       -4.24804688e-01,  5.37109375e-03, -2.18750000e-01, -1.24023438e-01,
        1.25000000e-01, -1.35253906e-01,  1.40625000e-01,  7.98339844e-02,
        1.36718750e-02,  1.72851562e-01,  7.69042969e-02,  1.36840820e-01,
        3.59191895e-02, -2.04833984e-01, -6.10351562e-05, -1.85546875e-02,
        1.68945312e-01,  8.98437500e-02,  3.71093750e-02, -1.36474609e-01,
       -4.47265625e-01, -3.90625000e-02, -7.17773438e-02,  9.76562500e-02],
      dtype=float32)

In [400]:
model.similarity('king','queen')

0.6510957

In [401]:
model.similarity('monkey','cricket')

0.1384329

In [402]:
model.similarity('snake','cricket')

0.06061651

In [403]:
model.doesnt_match(['PHP','Python','Java','monkey'])

'monkey'

In [404]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('West_Indies_cricket', 0.6987985968589783),
 ('Cricket_Board', 0.687838613986969),
 ('ODI', 0.6851662993431091)]

In [405]:
model.most_similar('india')

[('indian', 0.6967039704322815),
 ('america', 0.6589399576187134),
 ('canada', 0.6490967869758606),
 ('uk', 0.6221641898155212),
 ('american', 0.5897077322006226),
 ('microsoft', 0.5389088988304138),
 ('buy_microsoft', 0.524248480796814),
 ('viagra', 0.5152724981307983),
 ('cialis', 0.5047127604484558),
 ('India', 0.504573404788971)]

In [406]:
vec = model['king'] - model['man'] + model['woman']
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('queens', 0.5289887189865112),
 ('ruler', 0.5247419476509094)]

In [407]:
vec = model['INR'] - model['India'] + model['England']

In [408]:
model.most_similar([vec])

[('INR', 0.6442341208457947),
 ('GBP', 0.5040826797485352),
 ('England', 0.44649264216423035),
 ('£', 0.43340998888015747),
 ('Â_£', 0.4307197630405426),
 ('£_#.##m', 0.42561301589012146),
 ('GBP##', 0.42464491724967957),
 ('stg', 0.42324796319007874),
 ('EUR', 0.418365478515625),
 ('€', 0.4151178002357483)]

In [409]:
vec = model['football'] - model['hockey']
model.most_similar([vec])

[('football', 0.3350059688091278),
 ('Demps', 0.2860781252384186),
 ('Clowney', 0.27101752161979675),
 ('sacked', 0.2606068253517151),
 ('sack', 0.2597784698009491),
 ('Paschal', 0.25213107466697693),
 ('Diarra', 0.2514621317386627),
 ('Mustain', 0.25095781683921814),
 ('Grothe', 0.25030744075775146),
 ('Saban', 0.2491014152765274)]